using System.Text;

namespace Dyno.Core.Firmware;

/// <summary>One compile-time setting the user wants a different value for than the header declares.</summary>
/// <param name="Name">The <c>#define</c>'s name.</param>
/// <param name="File">The header it is declared in (<c>config.h</c> / <c>debug.h</c>).</param>
/// <param name="HeaderValue">What that header says — what a clean tree would build.</param>
/// <param name="Value">What the user saved, and so what the next build will use.</param>
public sealed record ConfigOverride(string Name, string File, string HeaderValue, string Value)
{
    public string Describe() => $"{Name} = {Value} (header: {HeaderValue})";
}

/// <summary>
/// Carries the compile-time settings saved on this PC into a firmware build, without ever touching
/// the committed headers.
///
/// config.h and debug.h each end with an <c>#if __has_include</c> of a generated overrides header,
/// which — being included last — wins over the defaults above it. This class writes those files:
/// an <c>#undef</c>/<c>#define</c> pair per changed setting and nothing else. The C sources are
/// untouched and still read the plain names, a clean checkout builds exactly what the headers say
/// (the files are absent, and <c>__has_include</c> is false), and the one generated file is a
/// complete answer to "what did this build change".
/// </summary>
public static class ConfigOverrides
{
    /// <summary>The headers that carry an <c>#if __has_include</c> hook, and so can be overridden.</summary>
    public static readonly IReadOnlyList<string> Headers = ["config.h", "debug.h"];

    /// <summary>Which generated header carries a given source header's overrides.</summary>
    public static string OverrideFileFor(string headerFileName) =>
        headerFileName switch
        {
            "config.h" => "config_overrides.h",
            "debug.h" => "debug_overrides.h",
            _ => throw new ArgumentException(
                $"No overrides header is wired up for '{headerFileName}'.",
                nameof(headerFileName)
            ),
        };

    /// <summary>
    /// Writes an overrides header for each of <see cref="Headers"/> — including an empty one where
    /// nothing is overridden, since a file left over from a previous build would otherwise keep
    /// applying settings the user has since reset.
    /// </summary>
    /// <returns>The files whose contents actually changed. An unchanged file is left alone rather
    /// than rewritten: ninja keys off mtimes, so a needless touch would recompile the whole firmware
    /// on every build.</returns>
    public static IReadOnlyList<string> Write(
        string configDirectory,
        IReadOnlyList<ConfigOverride> overrides
    )
    {
        var written = new List<string>();
        foreach (var header in Headers)
        {
            var fileName = OverrideFileFor(header);
            var path = Path.Combine(configDirectory, fileName);
            var text = Render(fileName, overrides.Where(o => o.File == header).ToList());

            if (File.Exists(path) && File.ReadAllText(path) == text)
            {
                continue;
            }
            File.WriteAllText(path, text);
            written.Add(fileName);
        }
        return written;
    }

    /// <summary>The text of one overrides header. Public for tests, and because it is exactly what
    /// the app shows when asked what a build will change.</summary>
    public static string Render(string fileName, IReadOnlyList<ConfigOverride> overrides)
    {
        var guard =
            $"INC_CONFIG_{Path.GetFileNameWithoutExtension(fileName).ToUpperInvariant()}_H_";
        var text = new StringBuilder()
            .AppendLine("// GENERATED by the Dyno desktop app — do not edit, and do not commit.")
            .AppendLine("//")
            .AppendLine(
                "// The compile-time settings you changed on the SysConfig page. Included at the foot"
            )
            .AppendLine(
                "// of the header it shadows, so these win; everything not listed here comes from that"
            )
            .AppendLine("// header as committed. Delete this file to build the defaults.")
            .AppendLine()
            .AppendLine($"#ifndef {guard}")
            .AppendLine($"#define {guard}")
            .AppendLine();

        if (overrides.Count == 0)
        {
            text.AppendLine("// Nothing is overridden.").AppendLine();
        }

        // Emitted in name order so the file is stable across runs: a build that changed nothing
        // must produce byte-identical text, or every build looks like a change to the compiler.
        foreach (
            var (name, _, headerValue, value) in overrides.OrderBy(
                o => o.Name,
                StringComparer.Ordinal
            )
        )
        {
            Validate(name, value);
            text.AppendLine($"// was {headerValue}")
                .AppendLine($"#undef  {name}")
                .AppendLine($"#define {name} {value}")
                .AppendLine();
        }

        return text.AppendLine($"#endif /* {guard} */").ToString();
    }

    /// <summary>A <c>#define</c> body is pasted into C as-is, so anything that could end the line
    /// early — a comment, a newline — would silently rewrite the header around it. The app's own
    /// validation already keeps these out; this is the backstop that makes the generated file safe
    /// to trust regardless of what put a row in the database.</summary>
    private static void Validate(string name, string value)
    {
        if (
            value.Length == 0
            || value.Contains('\n')
            || value.Contains('\r')
            || value.Contains("//", StringComparison.Ordinal)
            || value.Contains("/*", StringComparison.Ordinal)
        )
        {
            throw new InvalidOperationException(
                $"'{name}' has a saved value that cannot be written into a header: '{value}'."
            );
        }
    }
}
